docs/team/liufangrui.md
=> Create a skeletal Project Portfolio Page (PPP) (Fangrui)

src/main/java/seedu/address/logic/commands/AddInternshipCommand.java
Original error message does not indicate that contact person and interview date are optional
=> Add square brackets around contact person and interview date

src/main/java/seedu/address/logic/parser/AddInternshipCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/internship/Internship.java, src/main/java/seedu/address/model/internship/InternshipRole.java, src/main/java/seedu/address/storage/JsonAdaptedInternship.java, src/test/java/seedu/address/logic/commands/AddPersonCommandIntegrationTest.java
- Fix `InterviewDate` being a required field when it should be optional
- Fix `InternshipStatus` being optional when it should be a required field
- Fix `InternshipRole` `equals` method
- Fix incorrect code blocks for null checks in `JsonAdaptedInternship` `toModelType` method
- Fix `Id` fields not updating correctly after loading data from json
- Create methods for updating the next `Id` counters correctly in `AddressBook`
- Fix tests not working with updated `Id` behaviour
=> Fix general bugs with Internship

src/main/java/seedu/address/logic/parser/ParserUtil.java
Currently, status only accepts uppercase, so it is adjusted so that it also accepts lowercase, or a mix of lowercase and uppercase.
=> Adjust status to accept lowercase and mix of uppercase and lowercase

src/main/java/seedu/address/logic/commands/AddPersonCommand.java, src/main/java/seedu/address/model/AddressBook.java
An error where the person's ID increases abnormally is fixed as the bugfix was only applied to internship but not person previously.
Also fixes missing prompt for link index for the command to add person.
=> Fix person ID "random" increment (same fix as duplicate internship ID)

src/main/java/seedu/address/logic/parser/AddressBookParser.java
Changes should not affect the current implementation
Changes will be applied when COMMAND_WORD for respective Command classes is changed to flag usage
=> Update AddressBookParser to be able to parse flags

src/main/java/seedu/address/logic/commands/SortInternshipCommand.java, src/main/java/seedu/address/logic/commands/SortPersonCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/SortInternshipCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/internship/Internship.java, src/main/java/seedu/address/model/internship/InternshipStatus.java, src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
Allows sorting by:
* companyName
* interviewDate (order: Earlier to later dates; nulls at the end)
* internshipStatus (order: Completed, Accepted, Pending, Rejected)
Other misc changes:
* Remove redundant prefixes in CliSyntax
* Change SortPersonCommand to use -p flag
=> Implement Sort Internship functionality

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddPersonCommand.java
=> change command addp to add -p

src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/internship/Internship.java, src/main/java/seedu/address/model/internship/InternshipStatus.java
* Added a `BOOKMARKED` state
* Reordered the priority levels of `State` enums
* Allow single character shortcuts for `s/INTERNSHIP_STATUS`
=> Modify InternshipStatus.State

src/main/java/seedu/address/ui/InternshipCard.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/Extensions.css, src/main/resources/view/InternshipListCard.fxml
=> Update GUI to support different color status tags

src/main/resources/view/DarkTheme.css, src/main/resources/view/ResultDisplay.fxml
- Update GUI Result Display to have smaller font size and restrict to vertical scrolling only
- Update GUI to use rounded boxes for PersonCard and InternshipCard
- Edit odd and even PersonCard and InternshipCard colours to be more obvious
=> Update gui result display person and internship card

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/ListPersonCommand.java
Update user guide to match the changes
=> Update list person command to use flags

src/main/java/seedu/address/logic/commands/LinkCommand.java, src/main/java/seedu/address/logic/commands/UnlinkCommand.java, src/test/java/seedu/address/testutil/InternshipBuilder.java
LinkCommand Success message and Error messages now displays Internship displayed name rather than only company name
=> Update LinkCommand and UnlinkCommand Success message and Error messages

src/main/java/seedu/address/ui/MainWindow.java, src/main/resources/view/CommandBox.fxml, src/main/resources/view/Extensions.css, src/main/resources/view/LightTheme.css, src/main/resources/view/MainWindow.fxml
- Rework MainWindow functionality to support switching between multiple color themes
- Currently there are only 2 themes: Light and Dark, but more can be supported in future
- Resolve #138
=> Create Light Theme

docs/UserGuide.md, docs/_config.yml
- Reformate and add numbering to header
- Add Introduction Section with "What is InterNUS?" , "Persons" and "Internships" sub section
- Add General section for help, clear and exit command
- Add User Interface Section for Light and Dark Mode
- Add Data File section for saving and editing data file
###Reslove
- #212 
- #203 
- #200 
- #208 
- Changed interNUS to InterNUS in the Navigation Bar of UG
=> Update UG format

src/main/java/seedu/address/logic/commands/UnlinkCommand.java, src/main/java/seedu/address/logic/parser/UnlinkCommandParser.java
- fix unlink command only considering the first parameter when provided both person and internship
- slight adjustment to error message handling
=> Address Unlink Command Bugs

src/main/java/seedu/address/logic/commands/EditInternshipCommand.java, src/main/java/seedu/address/logic/commands/EditPersonCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
Model updates
- Add new `refreshPersonList()` and `refreshInternshipList()` functions in model that retains the previous sorting order
=> Address personlist/internshiplist not updating after editing linked counterpart

src/main/java/seedu/address/logic/commands/AddInternshipCommand.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/testutil/EditInternshipDescriptorBuilder.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/InternshipBuilder.java, src/test/java/seedu/address/testutil/InternshipUtil.java, src/test/java/seedu/address/testutil/PersonUtil.java
* Added test cases for all internship-related commands
* Fixed a bug in `AddInternshipCommand#equals()`
* Renamed some methods and variables in `Util` and `Builder` classes
* Removed an unnecessary method call
=> Write more test cases for AddressBookParser

src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/person/EmailTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/model/person/PhoneTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java
- add toString test in EmailTest, PhoneTest
- add company test in Person 
- add company test in ParserUtilTest
- update Javadoc in PersonBuilder
=> Update add -p testcase

docs/UserGuide.md, src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/AddInternshipCommand.java, src/main/java/seedu/address/logic/commands/AddPersonCommand.java, src/main/java/seedu/address/logic/commands/FindInternshipCommand.java, src/main/resources/view/LightTheme.css
* Update add internship and find commands in UG 
* Update command messages to match format in UG
* Fix bug where an out of range link index > list length was not throwing error in the add commands
* Fix bug where the right-click menu for command and result display box was showing white text on white background for light theme
=> Update UG and fix bugs

docs/UserGuide.md, src/main/java/seedu/address/model/internship/InternshipContainsKeywordsPredicate.java
- Status searching for find internship command now performs `startsWith` instead of `contains`
- Update UG accordingly
=> Fix bug with find internship command

docs/UserGuide.md
=> Fix add -p bug

docs/AboutUs.md, docs/UserGuide.md, docs/team/liufangrui.md
- Update PPP for 1.4
- Add full stops for some lines in user guide
=> Update PPP for 1.4

src/main/java/seedu/address/logic/commands/UnlinkCommand.java, src/main/java/seedu/address/logic/parser/LinkCommandParser.java, src/main/java/seedu/address/logic/parser/UnlinkCommandParser.java, src/test/java/seedu/address/logic/commands/AddInternshipCommandIntegrationTest.java, src/test/java/seedu/address/logic/commands/AddInternshipCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteInternshipCommandTest.java, src/test/java/seedu/address/model/internship/CompanyNameTest.java, src/test/java/seedu/address/model/internship/InternshipIdTest.java, src/test/java/seedu/address/model/internship/InternshipRoleTest.java, src/test/java/seedu/address/model/internship/InternshipStatusTest.java, src/test/java/seedu/address/model/internship/InternshipTest.java, src/test/java/seedu/address/model/internship/InterviewDateTest.java, src/test/java/seedu/address/model/person/PersonIdTest.java
- Add missing tests for field wrapper classes under Model
- Add tests for add internship and delete internship
- Add testing for Internship class
- Refactor Link and Unlink command parser to use common ParserUtil methods
=> Add Unit Tests

docs/DeveloperGuide.md
Page breaks added before every
except for those headings which come right after a
=> Add page breaks for DG

docs/DeveloperGuide.md
Fix: Note boxes broken up across pages
=> Fix DG bugs
